<?php
/** @var \Eadesigndev\RomCity\Block\Checkout\Cities $block */
?>

<div class="pp-buttons-container">
    <?php
    $cities = $block->citiesJson();
    ?>
</div>
<script>
    require(
        [
            'jquery'
        ],
        function ($) {
            $eaCitiesJson = <?php echo $cities?>;
        });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Esatic_DropdownCity/js/city-admin": {}
        }
    }
</script>


